name: airbnbprice
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  tflite_flutter: ^0.8.0
  csv: ^5.0.2
  google_maps_flutter: ^2.2.6




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/converted_model.tflite
     - assets/airbnb logo.PNG
     - assets/airbnbLogo2.PNG
     - assets/data0.csv
     - assets/data1.csv
     - assets/data2.csv
     - assets/data3.csv
     - assets/data4.csv
     - assets/data5.csv
     - assets/data6.csv
     - assets/data7.csv
     - assets/data8.csv
     - assets/data9.csv
     - assets/data10.csv
     - assets/data11.csv
     - assets/data12.csv
     - assets/data13.csv
     - assets/data14.csv
     - assets/data15.csv
     - assets/data16.csv
     - assets/data17.csv
     - assets/data18.csv
     - assets/data19.csv
     - assets/data20.csv
     - assets/data21.csv
     - assets/data22.csv
     - assets/data23.csv
     - assets/data24.csv
     - assets/data25.csv
     - assets/data26.csv
     - assets/data27.csv
     - assets/data28.csv
     - assets/data29.csv
     - assets/data30.csv
     - assets/data31.csv
     - assets/data32.csv
     - assets/data33.csv
     - assets/data34.csv
     - assets/data35.csv
     - assets/data36.csv
     - assets/data37.csv
     - assets/data38.csv
     - assets/data39.csv
     - assets/data40.csv
     - assets/data41.csv
     - assets/data42.csv
     - assets/data43.csv
     - assets/data44.csv
     - assets/data45.csv
     - assets/data46.csv
     - assets/data47.csv
     - assets/data48.csv
     - assets/data49.csv
     - assets/data50.csv
     - assets/data51.csv
     - assets/data52.csv
     - assets/data53.csv
     - assets/data54.csv
     - assets/data55.csv
     - assets/data56.csv
     - assets/data57.csv
     - assets/data58.csv
     - assets/data59.csv
     - assets/data60.csv
     - assets/data61.csv
     - assets/data62.csv
     - assets/data63.csv
     - assets/data64.csv
     - assets/data65.csv
     - assets/data66.csv
     - assets/data67.csv
     - assets/data68.csv
     - assets/data69.csv
     - assets/data70.csv
     - assets/data71.csv
     - assets/data72.csv
     - assets/data73.csv
     - assets/data74.csv
     - assets/data75.csv
     - assets/data76.csv
     - assets/data77.csv
     - assets/data78.csv
     - assets/data79.csv
     - assets/data80.csv
     - assets/data81.csv
     - assets/data82.csv
     - assets/data83.csv
     - assets/data84.csv
     - assets/data85.csv
     - assets/data86.csv
     - assets/data87.csv
     - assets/data88.csv
     - assets/data89.csv
     - assets/data90.csv
     - assets/data91.csv
     - assets/data92.csv
     - assets/data93.csv
     - assets/data94.csv
     - assets/data95.csv
     - assets/data96.csv
     - assets/data97.csv
     - assets/data98.csv
     - assets/data99.csv
     - assets/data100.csv
     - assets/data101.csv
     - assets/data102.csv
     - assets/data103.csv
     - assets/data104.csv
     - assets/data105.csv
     - assets/data106.csv
     - assets/data107.csv
     - assets/data108.csv
     - assets/data109.csv
     - assets/data110.csv
     - assets/data111.csv
     - assets/data112.csv
     - assets/data113.csv
     - assets/data114.csv
     - assets/data115.csv
     - assets/data116.csv
     - assets/data117.csv
     - assets/data118.csv
     - assets/data119.csv
     - assets/data120.csv
     - assets/data121.csv
     - assets/data122.csv
     - assets/data123.csv
     - assets/data124.csv
     - assets/data125.csv
     - assets/data126.csv
     - assets/data127.csv
     - assets/data128.csv
     - assets/data129.csv
     - assets/data130.csv
     - assets/data131.csv
     - assets/data132.csv
     - assets/data133.csv
     - assets/data134.csv
     - assets/data135.csv
     - assets/data136.csv
     - assets/data137.csv
     - assets/data138.csv
     - assets/data139.csv
     - assets/data140.csv
     - assets/data141.csv
     - assets/data142.csv
     - assets/data143.csv
     - assets/data144.csv
     - assets/data145.csv
     - assets/data146.csv
     - assets/data147.csv
     - assets/data148.csv
     - assets/data149.csv
     - assets/data150.csv
     - assets/data151.csv
     - assets/data152.csv
     - assets/data153.csv
     - assets/data154.csv
     - assets/data155.csv
     - assets/data156.csv
     - assets/data157.csv
     - assets/data158.csv
     - assets/data159.csv
     - assets/data160.csv
     - assets/data161.csv
     - assets/data162.csv
     - assets/data163.csv
     - assets/data164.csv
     - assets/data165.csv
     - assets/data166.csv
     - assets/data167.csv
     - assets/data168.csv
     - assets/data169.csv
     - assets/data170.csv
     - assets/data171.csv
     - assets/data172.csv
     - assets/data173.csv
     - assets/data174.csv
     - assets/data175.csv
     - assets/data176.csv
     - assets/data177.csv
     - assets/data178.csv
     - assets/data179.csv
     - assets/data180.csv
     - assets/data181.csv
     - assets/data182.csv
     - assets/data183.csv
     - assets/data184.csv
     - assets/data185.csv
     - assets/data186.csv
     - assets/data187.csv
     - assets/data188.csv
     - assets/data189.csv
     - assets/data190.csv
     - assets/data191.csv
     - assets/data192.csv
     - assets/data193.csv
     - assets/data194.csv
     - assets/data195.csv
     - assets/data196.csv
     - assets/data197.csv
     - assets/data198.csv
     - assets/data199.csv
     - assets/data200.csv
     - assets/data201.csv
     - assets/data202.csv
     - assets/data203.csv
     - assets/data204.csv
     - assets/data205.csv
     - assets/data206.csv
     - assets/data207.csv
     - assets/data208.csv
     - assets/data209.csv
     - assets/data210.csv
     - assets/data211.csv
     - assets/data212.csv
     - assets/data213.csv
     - assets/data214.csv
     - assets/data215.csv
     - assets/data216.csv
     - assets/data217.csv
     - assets/data218.csv
     - assets/data219.csv
     - assets/data220.csv
     - assets/data221.csv
     - assets/data222.csv



  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
